version: '3'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile-dev
        ports:
            - "8375:8375"
        volumes:
            - ./server:/app
            - appdata:/data
        environment:
            - MIX_ENV=${MIX_ENV}
            - VENUELESS_DB_NAME=venueless
            - VENUELESS_DB_USER=venueless
            - VENUELESS_DB_PASS=venueless
            - VENUELESS_DB_HOST=db
            - VENUELESS_DATA_DIR=/data
            - VENUELESS_MEDIA_URL=http://localhost:8375/media/
        entrypoint: ["bash", "/app/docker-dev-entrypoint.sh"]
        depends_on:
            - db
    # webapp:
    #     build:
    #         context: ./webapp
    #         dockerfile: Dockerfile-dev
    #     ports:
    #         - "8880:8880"
    #     volumes:
    #         - ./webapp:/app:ro
    #     command: ["npm", "start", "--", "--host", "0.0.0.0"]
    db:
        image: "postgres:13"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=venueless
            - POSTGRES_PASSWORD=venueless
volumes:
    postgres_data:
    appdata:
networks:
  default:
    ipam:
      config:
        - subnet: 172.177.0.0/16
