FROM elixir:latest

RUN apt-get update -qq && apt-get install -y inotify-tools

COPY mix.* /

RUN mix local.hex --force && \
    mix local.rebar --force

RUN mix deps.get
RUN mix deps.compile

WORKDIR /app
ENV MIX_DEPS_PATH=/deps
ENV MIX_BUILD_ROOT=/_build
EXPOSE 8375
